import { Crown, LockKeyhole, Medal, Save, Trophy } from "lucide-react";
import { useState } from "react";

export type LeaderboardRow = { rank: number; displayName: string; level: number; weeklyXp: number; lifetimeXp: number; isCurrentUser: boolean };

type Props = { signedIn: boolean; rows: LeaderboardRow[]; displayName: string; loading: boolean; error: string; onPeriodChange: (period: "weekly" | "all-time") => void; onSaveName: (name: string) => Promise<void>; onSignIn: () => void };

export function Leaderboard({ signedIn, rows, displayName, loading, error, onPeriodChange, onSaveName, onSignIn }: Props) {
  const [period, setPeriod] = useState<"weekly" | "all-time">("weekly");
  const [name, setName] = useState(displayName);
  const [saving, setSaving] = useState(false);
  const changePeriod = (next: "weekly" | "all-time") => { setPeriod(next); onPeriodChange(next); };
  if (!signedIn) return <div className="rounded-3xl border border-zinc-200 bg-white p-8 text-center shadow-sm"><LockKeyhole className="mx-auto h-10 w-10 text-indigo-600" /><h2 className="mt-4 text-3xl font-semibold">Sign in to compete</h2><p className="mx-auto mt-2 max-w-md text-zinc-500">Guest XP stays private on this device. An account is required for the global leaderboard.</p><button onClick={onSignIn} className="mt-5 min-h-12 rounded-2xl bg-indigo-600 px-6 font-semibold text-white">Sign in or create account</button></div>;
  return <div className="space-y-5"><header><p className="text-sm font-semibold text-indigo-700">GLOBAL PRODUCTIVITY</p><h2 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">Leaderboard</h2><p className="mt-2 text-zinc-500">Weekly XP keeps competition fresh. Only your public display name is shown.</p></header>
    <section className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><label className="min-w-0 flex-1"><span className="text-sm font-semibold">Public display name</span><span className="mt-1 block text-xs text-zinc-500">Your email and account ID are never displayed.</span><input value={name || displayName} onChange={(event) => setName(event.target.value)} maxLength={30} className="mt-2 min-h-12 w-full rounded-xl border border-zinc-200 px-4" /></label><button onClick={async () => { setSaving(true); await onSaveName(name || displayName); setSaving(false); }} disabled={saving || (name || displayName).trim().length < 3} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save name"}</button></div></section>
    <section className="overflow-hidden rounded-3xl border border-zinc-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-zinc-200 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-center gap-3"><span className="rounded-2xl bg-amber-100 p-3 text-amber-700"><Trophy className="h-6 w-6" /></span><div><h3 className="text-xl font-semibold">Top students</h3><p className="text-sm text-zinc-500">Ranked by {period === "weekly" ? "XP earned this week" : "lifetime XP"}</p></div></div><div className="flex rounded-xl bg-zinc-100 p-1"><button onClick={() => changePeriod("weekly")} className={`min-h-10 rounded-lg px-4 text-sm font-semibold ${period === "weekly" ? "bg-white text-indigo-700 shadow-sm" : "text-zinc-500"}`}>Weekly</button><button onClick={() => changePeriod("all-time")} className={`min-h-10 rounded-lg px-4 text-sm font-semibold ${period === "all-time" ? "bg-white text-indigo-700 shadow-sm" : "text-zinc-500"}`}>All-time</button></div></div>
      {error && <p className="m-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
      {loading ? <p className="p-8 text-center text-zinc-500">Loading leaderboard…</p> : <div className="divide-y divide-zinc-100">{rows.map((row) => <div key={`${row.rank}-${row.displayName}`} className={`grid grid-cols-[48px_minmax(0,1fr)_auto] items-center gap-3 p-4 sm:grid-cols-[64px_minmax(0,1fr)_100px_130px] sm:px-6 ${row.isCurrentUser ? "bg-indigo-50" : ""}`}><div className="flex items-center justify-center font-semibold text-zinc-500">{row.rank <= 3 ? row.rank === 1 ? <Crown className="h-6 w-6 text-amber-500" /> : <Medal className={`h-6 w-6 ${row.rank === 2 ? "text-slate-400" : "text-amber-700"}`} /> : `#${row.rank}`}</div><div className="min-w-0"><p className="truncate font-semibold text-zinc-950">{row.displayName}{row.isCurrentUser ? " (You)" : ""}</p><p className="text-sm text-zinc-500">Level {row.level}</p></div><p className="hidden text-sm font-medium text-zinc-500 sm:block">{row.lifetimeXp} total</p><p className="text-right font-semibold text-indigo-700">{period === "weekly" ? row.weeklyXp : row.lifetimeXp} XP</p></div>)}{rows.length === 0 && <p className="p-8 text-center text-zinc-500">No rankings yet. Complete productive work to start the board.</p>}</div>}
    </section></div>;
}
